baseURL = ''
languageCode = 'en-us'
title = 'Thomistic Thinker'
theme = 'poison'

[params]
    brand = "Thomistic Thinker"                      # name of your site - appears in the sidebar
    brand_image = "/images/logo.jpg"
    # path to the image shown in the sidebar
    dark_mode = false                      # optional - defaults to false